# Generated by Django 3.2.16 on 2024-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
