# Generated by Django 3.2.16 on 2024-12-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0002_alter_station_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='Storage_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
