# Generated by Django 3.2.16 on 2024-12-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0003_auto_20241214_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
