# Generated by Django 5.1.4 on 2024-12-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0004_alter_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geoportal.sectors'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='territories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoportal.provinces')),
            ],
        ),
        migrations.AddField(
            model_name='sectors',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoportal.territories'),
        ),
    ]
