# Generated by Django 5.1.4 on 2024-12-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0005_provinces_sectors_station_sector_territories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='Opening_hours',
            new_name='opening_hours',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='Storage_capacity',
            new_name='storage_capacity',
        ),
        migrations.AddField(
            model_name='station',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geoportal.provinces'),
        ),
        migrations.AddField(
            model_name='station',
            name='territory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geoportal.territories'),
            preserve_default=False,
        ),
    ]
