# Generated by Django 5.1.4 on 2025-01-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0007_alter_station_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='provinces',
            name='p_cent_lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='provinces',
            name='p_cent_long',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sectors',
            name='s_cent_lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sectors',
            name='s_cent_long',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='territories',
            name='t_cent_lat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='territories',
            name='t_cent_long',
            field=models.CharField(default='', max_length=20),
        ),
    ]
