# Generated by Django 5.1.4 on 2025-01-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0008_provinces_p_cent_lat_provinces_p_cent_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinces',
            name='p_cent_lat',
            field=models.FloatField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='provinces',
            name='p_cent_long',
            field=models.FloatField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='s_cent_lat',
            field=models.FloatField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectors',
            name='s_cent_long',
            field=models.FloatField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='territories',
            name='t_cent_lat',
            field=models.FloatField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='territories',
            name='t_cent_long',
            field=models.FloatField(default='', max_length=20),
        ),
    ]
